/**
 * Stable business error codes.
 *
 * Postgres raises these through `app.fail(code, message)`, which puts the code in
 * the error HINT and the customer-safe message in MESSAGE. Edge Functions return
 * them as `{ error: { code, message, details } }`.
 *
 * Clients map a code to localised copy. They must never parse the message text.
 */
export const ERROR_CODES = {
    // ── Auth & account ──
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
    PRIVILEGE_ESCALATION_BLOCKED: 'PRIVILEGE_ESCALATION_BLOCKED',
    RATE_LIMITED: 'RATE_LIMITED',

    // ── Catalog ──
    ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
    ITEM_UNAVAILABLE: 'ITEM_UNAVAILABLE',
    VARIANT_REQUIRED: 'VARIANT_REQUIRED',
    VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
    MODIFIER_INVALID: 'MODIFIER_INVALID',
    MODIFIER_UNAVAILABLE: 'MODIFIER_UNAVAILABLE',
    MODIFIER_SELECTION_REQUIRED: 'MODIFIER_SELECTION_REQUIRED',
    MODIFIER_SELECTION_EXCEEDED: 'MODIFIER_SELECTION_EXCEEDED',
    QUANTITY_LIMIT_EXCEEDED: 'QUANTITY_LIMIT_EXCEEDED',
    INVALID_QUANTITY: 'INVALID_QUANTITY',

    // ── Cart & checkout ──
    CART_NOT_FOUND: 'CART_NOT_FOUND',
    CART_EMPTY: 'CART_EMPTY',
    CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
    CHECKOUT_INVALID: 'CHECKOUT_INVALID',
    MIN_ORDER_NOT_MET: 'MIN_ORDER_NOT_MET',
    ADDRESS_REQUIRED: 'ADDRESS_REQUIRED',
    ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
    ADDRESS_NOT_SERVICEABLE: 'ADDRESS_NOT_SERVICEABLE',
    OUTSIDE_MAX_DISTANCE: 'OUTSIDE_MAX_DISTANCE',
    PICKUP_UNAVAILABLE: 'PICKUP_UNAVAILABLE',
    PICKUP_DISABLED: 'PICKUP_DISABLED',
    SCHEDULE_REQUIRED: 'SCHEDULE_REQUIRED',
    SCHEDULE_TOO_SOON: 'SCHEDULE_TOO_SOON',
    SCHEDULE_TOO_FAR: 'SCHEDULE_TOO_FAR',
    SCHEDULING_DISABLED: 'SCHEDULING_DISABLED',

    // ── Store state ──
    RESTAURANT_CLOSED: 'RESTAURANT_CLOSED',
    ORDERING_PAUSED: 'ORDERING_PAUSED',
    OUTSIDE_TRADING_HOURS: 'OUTSIDE_TRADING_HOURS',
    TOO_BUSY: 'TOO_BUSY',
    MAINTENANCE_MODE: 'MAINTENANCE_MODE',
    BRANCH_NOT_FOUND: 'BRANCH_NOT_FOUND',
    BRANCH_INACTIVE: 'BRANCH_INACTIVE',
    CLOSURE_REASON_REQUIRED: 'CLOSURE_REASON_REQUIRED',

    // ── Coupons & promotions ──
    COUPON_INVALID: 'COUPON_INVALID',
    COUPON_INACTIVE: 'COUPON_INACTIVE',
    COUPON_EXPIRED: 'COUPON_EXPIRED',
    COUPON_NOT_STARTED: 'COUPON_NOT_STARTED',
    COUPON_EXHAUSTED: 'COUPON_EXHAUSTED',
    COUPON_ALREADY_USED: 'COUPON_ALREADY_USED',
    COUPON_NOT_ELIGIBLE: 'COUPON_NOT_ELIGIBLE',
    COUPON_NOT_APPLICABLE: 'COUPON_NOT_APPLICABLE',
    COUPON_FIRST_ORDER_ONLY: 'COUPON_FIRST_ORDER_ONLY',
    COUPON_MIN_ORDER_NOT_MET: 'COUPON_MIN_ORDER_NOT_MET',
    COUPON_NO_ELIGIBLE_ITEMS: 'COUPON_NO_ELIGIBLE_ITEMS',
    COUPON_NOT_VALID_TODAY: 'COUPON_NOT_VALID_TODAY',
    COUPON_NOT_VALID_NOW: 'COUPON_NOT_VALID_NOW',
    COUPON_PAYMENT_RESTRICTED: 'COUPON_PAYMENT_RESTRICTED',
    COUPON_RULE_NOT_MET: 'COUPON_RULE_NOT_MET',
    BETTER_OFFER_APPLIED: 'BETTER_OFFER_APPLIED',

    // ── Orders ──
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    ORDER_ITEM_NOT_FOUND: 'ORDER_ITEM_NOT_FOUND',
    ORDER_ALREADY_CREATED: 'ORDER_ALREADY_CREATED',
    IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
    INVALID_ORDER_TRANSITION: 'INVALID_ORDER_TRANSITION',
    CANCELLATION_NOT_ALLOWED: 'CANCELLATION_NOT_ALLOWED',
    CANCELLATION_LIMIT_REACHED: 'CANCELLATION_LIMIT_REACHED',
    ITEM_CANCEL_NOT_ALLOWED: 'ITEM_CANCEL_NOT_ALLOWED',
    LAST_ITEM_CANNOT_BE_CANCELLED: 'LAST_ITEM_CANNOT_BE_CANCELLED',

    // ── Payments ──
    PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
    PAYMENT_SIGNATURE_INVALID: 'PAYMENT_SIGNATURE_INVALID',
    PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
    PAYMENT_NOT_REQUIRED: 'PAYMENT_NOT_REQUIRED',
    GATEWAY_ERROR: 'GATEWAY_ERROR',
    COD_UNAVAILABLE: 'COD_UNAVAILABLE',
    COD_LIMIT_EXCEEDED: 'COD_LIMIT_EXCEEDED',
    COD_MIN_ORDER_NOT_MET: 'COD_MIN_ORDER_NOT_MET',
    COD_AMOUNT_MISMATCH: 'COD_AMOUNT_MISMATCH',
    INSUFFICIENT_WALLET_BALANCE: 'INSUFFICIENT_WALLET_BALANCE',
    WALLET_FROZEN: 'WALLET_FROZEN',
    INSUFFICIENT_LOYALTY_POINTS: 'INSUFFICIENT_LOYALTY_POINTS',

    // ── Refunds ──
    REFUND_NOT_FOUND: 'REFUND_NOT_FOUND',
    REFUND_NOT_ALLOWED: 'REFUND_NOT_ALLOWED',
    REFUND_NOT_PENDING: 'REFUND_NOT_PENDING',
    REFUND_ITEMS_REQUIRED: 'REFUND_ITEMS_REQUIRED',
    REFUND_AMOUNT_REQUIRED: 'REFUND_AMOUNT_REQUIRED',
    INVALID_REFUND_AMOUNT: 'INVALID_REFUND_AMOUNT',
    REFUND_AMOUNT_EXCEEDS_REFUNDABLE: 'REFUND_AMOUNT_EXCEEDS_REFUNDABLE',
    REFUND_QUANTITY_EXCEEDED: 'REFUND_QUANTITY_EXCEEDED',
    REFUND_EXCEEDS_ROLE_LIMIT: 'REFUND_EXCEEDS_ROLE_LIMIT',
    SELF_APPROVAL_NOT_ALLOWED: 'SELF_APPROVAL_NOT_ALLOWED',

    // ── Delivery ──
    NOT_A_DELIVERY_PARTNER: 'NOT_A_DELIVERY_PARTNER',
    RIDER_NOT_ACTIVE: 'RIDER_NOT_ACTIVE',
    RIDER_NOT_FOUND: 'RIDER_NOT_FOUND',
    RIDER_AT_CAPACITY: 'RIDER_AT_CAPACITY',
    RIDER_WRONG_BRANCH: 'RIDER_WRONG_BRANCH',
    NO_DELIVERY_PARTNER: 'NO_DELIVERY_PARTNER',
    ACTIVE_DELIVERIES_PENDING: 'ACTIVE_DELIVERIES_PENDING',
    ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
    ASSIGNMENT_EXPIRED: 'ASSIGNMENT_EXPIRED',
    NOT_A_DELIVERY_ORDER: 'NOT_A_DELIVERY_ORDER',
    ORDER_NOT_ASSIGNABLE: 'ORDER_NOT_ASSIGNABLE',
    ORDER_ALREADY_PICKED_UP: 'ORDER_ALREADY_PICKED_UP',
    DELIVERY_NOT_IN_PROGRESS: 'DELIVERY_NOT_IN_PROGRESS',
    DELIVERY_OTP_REQUIRED: 'DELIVERY_OTP_REQUIRED',
    DELIVERY_OTP_INVALID: 'DELIVERY_OTP_INVALID',
    DELIVERY_OTP_UNAVAILABLE: 'DELIVERY_OTP_UNAVAILABLE',
    PICKUP_CODE_INVALID: 'PICKUP_CODE_INVALID',
    PICKUP_CODE_UNAVAILABLE: 'PICKUP_CODE_UNAVAILABLE',
    TOO_MANY_ATTEMPTS: 'TOO_MANY_ATTEMPTS',
    OVERRIDE_NOT_PERMITTED: 'OVERRIDE_NOT_PERMITTED',

    // ── Support & reviews ──
    TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',
    REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
    REVIEW_ALREADY_SUBMITTED: 'REVIEW_ALREADY_SUBMITTED',

    // ── Misc ──
    CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
    INVOICE_NOT_AVAILABLE: 'INVOICE_NOT_AVAILABLE',
    REORDER_UNAVAILABLE: 'REORDER_UNAVAILABLE',
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    UNKNOWN_CADENCE: 'UNKNOWN_CADENCE',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NETWORK_ERROR: 'NETWORK_ERROR',
    TIMEOUT: 'TIMEOUT',
    UNKNOWN: 'UNKNOWN',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Shape returned by every Edge Function on failure. */
export interface ApiError {
    code: ErrorCode | string;
    message: string;
    details?: Record<string, unknown> | null;
    requestId?: string;
}

export interface ApiFailure {
    ok: false;
    error: ApiError;
}

export interface ApiSuccess<T> {
    ok: true;
    data: T;
    requestId?: string;
}

export type ApiResult<T> = ApiSuccess<T> | ApiFailure;

/**
 * Errors the customer can resolve by retrying the same action unchanged.
 * Anything else needs the UI to change state (fix the cart, pick an address…).
 */
export const RETRYABLE_ERROR_CODES: readonly string[] = [
    ERROR_CODES.NETWORK_ERROR,
    ERROR_CODES.TIMEOUT,
    ERROR_CODES.GATEWAY_ERROR,
    ERROR_CODES.RATE_LIMITED,
];

export function isRetryable(code: string): boolean {
    return RETRYABLE_ERROR_CODES.includes(code);
}

/** Customer-facing fallback copy, used when the server sends no message. */
export const ERROR_FALLBACK_MESSAGES: Partial<Record<string, string>> = {
    [ERROR_CODES.NETWORK_ERROR]: 'You appear to be offline. Check your connection and try again.',
    [ERROR_CODES.TIMEOUT]: 'That took too long. Please try again.',
    [ERROR_CODES.RATE_LIMITED]: 'Too many attempts. Please wait a moment.',
    [ERROR_CODES.UNAUTHENTICATED]: 'Please sign in to continue.',
    [ERROR_CODES.PERMISSION_DENIED]: 'You do not have permission to do that.',
    [ERROR_CODES.UNKNOWN]: 'Something went wrong on our side. Please try again.',
};
