-- ═══════════════════════════════════════════════════════════════════════════
-- 0029 · RIDER LIFECYCLE
--
-- `rider_onboarding_status` describes a progression —
-- PENDING → DOCUMENTS_SUBMITTED → VERIFIED → ACTIVE — but nothing enforced it.
-- Documents were inserted straight through a table grant, activation was a raw
-- service-role UPDATE from an edge function, and `partner_code` was never
-- generated by anything.
--
-- This migration gives each transition an owner:
--
--   rider  · submit_rider_document      PENDING → DOCUMENTS_SUBMITTED
--   staff  · review_rider_document      DOCUMENTS_SUBMITTED → VERIFIED
--   staff  · approve_rider              VERIFIED → ACTIVE  (+ partner code)
--   staff  · suspend_rider              ACTIVE → SUSPENDED
--   staff  · post_delivery_earning      incentives, penalties, adjustments
--
-- It also wires up two pieces of configuration that existed but were never read:
-- peak-hour payout, and the distance from the rider to the store at assignment.
-- ═══════════════════════════════════════════════════════════════════════════

-- ─── Which documents an outlet insists on ───────────────────────────────────
-- Configurable rather than hard-coded: a bicycle rider has no vehicle RC, and
-- what an outlet demands changes with local rules.
insert into public.settings (key, value, value_type, "group", label, description, is_public)
values
  (
    'rider.required_documents',
    '["DRIVING_LICENCE", "AADHAAR", "PROFILE_PHOTO"]'::jsonb,
    'array',
    'delivery',
    'Required rider documents',
    'Document types a delivery partner must submit before they can be verified.',
    false
  ),
  (
    'delivery.partner_code_prefix',
    '"BB"'::jsonb,
    'string',
    'delivery',
    'Partner code prefix',
    'Prefix for generated delivery partner codes, e.g. BB-BKP-001.',
    false
  )
on conflict (key) do nothing;

-- ─── Templates for the onboarding events added in the previous migration ────
insert into public.notification_templates (event, channel, locale, title, body, action_route, variables)
values
  ('RIDER_DOCUMENT_REVIEWED', 'PUSH', 'en', '{{title}}',
   '{{message}}', null, array['title', 'message']),
  ('RIDER_DOCUMENT_REVIEWED', 'IN_APP', 'en', '{{title}}',
   '{{message}}', null, array['title', 'message']),
  ('RIDER_APPROVED', 'PUSH', 'en', 'You are approved 🎉',
   'Welcome aboard. Your partner code is {{partner_code}}. Go on duty to start receiving deliveries.',
   null, array['partner_code']),
  ('RIDER_APPROVED', 'IN_APP', 'en', 'You are approved',
   'Your partner code is {{partner_code}}. Go on duty to start receiving deliveries.',
   null, array['partner_code']),
  ('RIDER_APPROVED', 'SMS', 'en', null,
   'Bites Box: your delivery partner account is active. Partner code {{partner_code}}.',
   null, array['partner_code']),
  ('RIDER_SUSPENDED', 'IN_APP', 'en', 'Your account is on hold',
   'Please speak to your manager. Reason: {{reason}}', null, array['reason'])
on conflict (event, channel, locale) do nothing;

create or replace function app.required_rider_documents()
returns public.rider_document_type[]
language sql
stable
set search_path = ''
as $$
  select coalesce(
    (
      select array_agg(value::public.rider_document_type)
      from jsonb_array_elements_text(app.setting('rider.required_documents', '[]'::jsonb))
    ),
    array['DRIVING_LICENCE', 'AADHAAR', 'PROFILE_PHOTO']::public.rider_document_type[]
  );
$$;

-- ─── Partner code ───────────────────────────────────────────────────────────
-- Human-readable and stable: it appears on COD settlement sheets and on the
-- kitchen ticket, so it must be short, unambiguous and never reused.
create or replace function app.next_partner_code(p_branch_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_branch_code text;
  v_prefix text := app.setting_text('delivery.partner_code_prefix', 'BB');
  v_candidate text;
  v_sequence int;
begin
  select coalesce(nullif(btrim(code), ''), 'BX')
  into v_branch_code
  from public.branches
  where id = p_branch_id;

  select count(*) + 1 into v_sequence
  from public.delivery_partners
  where branch_id = p_branch_id;

  -- Bounded retry: partner rows can be soft-deleted, so a count can collide.
  for i in 0 .. 200 loop
    v_candidate := format('%s-%s-%s', v_prefix, upper(v_branch_code), lpad((v_sequence + i)::text, 3, '0'));

    if not exists (
      select 1 from public.delivery_partners where partner_code = v_candidate
    ) then
      return v_candidate;
    end if;
  end loop;

  -- Fall back to something guaranteed unique rather than failing onboarding.
  return format('%s-%s', v_prefix, app.random_alnum_code(8));
end;
$$;

-- ═══════════════════════════════════════════════════════════════════════════
-- RIDER-FACING: submit documents
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.my_rider_onboarding()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_partner public.delivery_partners;
  v_required public.rider_document_type[] := app.required_rider_documents();
begin
  select * into v_partner
  from public.delivery_partners
  where user_id = auth.uid() and deleted_at is null;

  if not found then
    perform app.fail('NOT_A_DELIVERY_PARTNER', 'This account is not a delivery partner.');
  end if;

  return jsonb_build_object(
    'delivery_partner_id', v_partner.id,
    'onboarding_status', v_partner.onboarding_status,
    'partner_code', v_partner.partner_code,
    'rejection_reason', v_partner.rejection_reason,
    'suspended_reason', v_partner.suspended_reason,
    'suspended_until', v_partner.suspended_until,
    'required_documents', to_jsonb(v_required),
    'documents', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', d.id,
          'document_type', d.document_type,
          'status', d.status,
          'document_number', d.document_number,
          'expires_on', d.expires_on,
          'rejection_reason', d.rejection_reason,
          'reviewed_at', d.reviewed_at,
          'is_required', d.document_type = any (v_required),
          'created_at', d.created_at
        ) order by d.created_at
      )
      from public.delivery_partner_documents d
      where d.delivery_partner_id = v_partner.id
    ), '[]'::jsonb),
    -- Everything the rider still owes us, so the app can render a checklist.
    'outstanding', coalesce((
      select jsonb_agg(t)
      from unnest(v_required) as t
      where not exists (
        select 1 from public.delivery_partner_documents d
        where d.delivery_partner_id = v_partner.id
          and d.document_type = t
          and d.status in ('PENDING', 'APPROVED')
      )
    ), '[]'::jsonb)
  );
end;
$$;

comment on function public.my_rider_onboarding is
  'The rider''s own onboarding checklist: what is submitted, approved and still outstanding.';

create or replace function public.submit_rider_document(
  p_document_type public.rider_document_type,
  p_storage_path text,
  p_document_number text default null,
  p_issued_on date default null,
  p_expires_on date default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_partner public.delivery_partners;
  v_document public.delivery_partner_documents;
  v_required public.rider_document_type[] := app.required_rider_documents();
  v_outstanding int;
begin
  select * into v_partner
  from public.delivery_partners
  where user_id = auth.uid() and deleted_at is null
  for update;

  if not found then
    perform app.fail('NOT_A_DELIVERY_PARTNER', 'This account is not a delivery partner.');
  end if;

  if v_partner.onboarding_status in ('REJECTED', 'SUSPENDED') then
    perform app.fail(
      'RIDER_NOT_ACTIVE',
      'Your account cannot accept new documents. Please speak to your manager.',
      jsonb_build_object('onboarding_status', v_partner.onboarding_status)
    );
  end if;

  if btrim(coalesce(p_storage_path, '')) = '' then
    perform app.fail('CHECKOUT_INVALID', 'Upload the document before submitting it.');
  end if;

  -- The rider owns the uid/ prefix in the rider-documents bucket; refusing any
  -- other path stops a crafted request pointing at somebody else's file.
  if split_part(p_storage_path, '/', 1) <> auth.uid()::text then
    perform app.fail(
      'PERMISSION_DENIED',
      'That file does not belong to you.',
      jsonb_build_object('storage_path', p_storage_path)
    );
  end if;

  if p_expires_on is not null and p_expires_on < current_date then
    perform app.fail('CHECKOUT_INVALID', 'That document has already expired.');
  end if;

  -- Re-submitting replaces the previous attempt and re-opens the review.
  insert into public.delivery_partner_documents as d (
    delivery_partner_id, document_type, storage_path, document_number,
    issued_on, expires_on, status
  )
  values (
    v_partner.id, p_document_type, p_storage_path, p_document_number,
    p_issued_on, p_expires_on, 'PENDING'
  )
  on conflict (delivery_partner_id, document_type) do update
    set storage_path = excluded.storage_path,
        document_number = coalesce(excluded.document_number, d.document_number),
        issued_on = coalesce(excluded.issued_on, d.issued_on),
        expires_on = coalesce(excluded.expires_on, d.expires_on),
        status = 'PENDING',
        reviewed_by = null,
        reviewed_at = null,
        rejection_reason = null,
        updated_at = now()
  returning * into v_document;

  select count(*) into v_outstanding
  from unnest(v_required) as t
  where not exists (
    select 1 from public.delivery_partner_documents d2
    where d2.delivery_partner_id = v_partner.id
      and d2.document_type = t
      and d2.status in ('PENDING', 'APPROVED')
  );

  -- Only advance out of PENDING; a verified rider re-uploading an expiring
  -- licence should not be knocked back down the funnel.
  if v_outstanding = 0 and v_partner.onboarding_status = 'PENDING' then
    update public.delivery_partners
    set onboarding_status = 'DOCUMENTS_SUBMITTED', updated_at = now()
    where id = v_partner.id;
  end if;

  return jsonb_build_object(
    'document_id', v_document.id,
    'document_type', v_document.document_type,
    'status', v_document.status,
    'outstanding_count', v_outstanding,
    'onboarding_status', case
      when v_outstanding = 0 and v_partner.onboarding_status = 'PENDING'
      then 'DOCUMENTS_SUBMITTED'
      else v_partner.onboarding_status
    end
  );
end;
$$;

comment on function public.submit_rider_document is
  'Rider uploads or replaces one onboarding document. Advances PENDING → DOCUMENTS_SUBMITTED once nothing is outstanding.';

-- ═══════════════════════════════════════════════════════════════════════════
-- STAFF-FACING: review, approve, suspend
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.review_rider_document(
  p_document_id uuid,
  p_approve boolean,
  p_rejection_reason text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_document public.delivery_partner_documents;
  v_partner public.delivery_partners;
  v_required public.rider_document_type[] := app.required_rider_documents();
  v_pending int;
  v_next public.rider_onboarding_status;
begin
  select * into v_document
  from public.delivery_partner_documents
  where id = p_document_id
  for update;

  if not found then
    perform app.fail('ITEM_NOT_FOUND', 'That document no longer exists.');
  end if;

  select * into v_partner
  from public.delivery_partners
  where id = v_document.delivery_partner_id;

  perform app.require_permission('rider.approve', v_partner.branch_id);

  if not p_approve and btrim(coalesce(p_rejection_reason, '')) = '' then
    perform app.fail('CHECKOUT_INVALID', 'Give a reason so the rider knows what to fix.');
  end if;

  update public.delivery_partner_documents
  set status = case
        when p_approve then 'APPROVED'::public.document_status
        else 'REJECTED'::public.document_status
      end,
      reviewed_by = auth.uid(),
      reviewed_at = now(),
      rejection_reason = case when p_approve then null else p_rejection_reason end,
      updated_at = now()
  where id = p_document_id;

  -- Verified means every required document is approved — not merely reviewed.
  select count(*) into v_pending
  from unnest(v_required) as t
  where not exists (
    select 1 from public.delivery_partner_documents d
    where d.delivery_partner_id = v_partner.id
      and d.document_type = t
      and d.status = 'APPROVED'
  );

  v_next := v_partner.onboarding_status;

  if v_pending = 0 and v_partner.onboarding_status = 'DOCUMENTS_SUBMITTED' then
    v_next := 'VERIFIED';
  elsif not p_approve and v_partner.onboarding_status = 'VERIFIED' then
    -- A rejected document invalidates a verification that has not been activated.
    v_next := 'DOCUMENTS_SUBMITTED';
  end if;

  if v_next <> v_partner.onboarding_status then
    update public.delivery_partners
    set onboarding_status = v_next, updated_at = now()
    where id = v_partner.id;
  end if;

  perform app.audit(
    'UPDATE',
    'delivery_partner_document',
    p_document_id::text,
    jsonb_build_object('status', v_document.status),
    jsonb_build_object(
      'status', case when p_approve then 'APPROVED' else 'REJECTED' end,
      'onboarding_status', v_next
    ),
    p_rejection_reason,
    format('%s · %s', v_partner.full_name, v_document.document_type),
    v_partner.branch_id
  );

  perform app.enqueue_notification(
    v_partner.user_id,
    'RIDER_DOCUMENT_REVIEWED',
    jsonb_build_object(
      'title', case when p_approve then 'Document approved' else 'Document needs attention' end,
      'message', case
        when p_approve then format('Your %s has been approved.', lower(replace(v_document.document_type::text, '_', ' ')))
        else format('Your %s was not accepted: %s',
                    lower(replace(v_document.document_type::text, '_', ' ')),
                    coalesce(p_rejection_reason, 'please re-upload it'))
      end
    ),
    array['PUSH', 'IN_APP']::public.notification_channel[],
    null,
    format('rider_doc:%s:%s', p_document_id, case when p_approve then 'ok' else 'no' end)
  );

  return jsonb_build_object(
    'document_id', p_document_id,
    'status', case when p_approve then 'APPROVED' else 'REJECTED' end,
    'onboarding_status', v_next,
    'ready_to_activate', v_next = 'VERIFIED'
  );
end;
$$;

create or replace function public.approve_rider(
  p_delivery_partner_id uuid,
  p_note text default null,
  p_force boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_partner public.delivery_partners;
  v_code text;
begin
  select * into v_partner
  from public.delivery_partners
  where id = p_delivery_partner_id and deleted_at is null
  for update;

  if not found then
    perform app.fail('RIDER_NOT_FOUND', 'Delivery partner not found.');
  end if;

  perform app.require_permission('rider.approve', v_partner.branch_id);

  if v_partner.onboarding_status = 'ACTIVE' then
    return jsonb_build_object(
      'delivery_partner_id', p_delivery_partner_id,
      'onboarding_status', 'ACTIVE',
      'partner_code', v_partner.partner_code,
      'changed', false
    );
  end if;

  -- Activating an unverified rider is possible but explicit: a manager who
  -- vouches for someone whose paperwork is still coming has to say so, and the
  -- audit entry records that they did.
  if v_partner.onboarding_status <> 'VERIFIED' and not p_force then
    perform app.fail(
      'RIDER_NOT_ACTIVE',
      format(
        'This partner is %s. Approve their documents first, or override deliberately.',
        replace(lower(v_partner.onboarding_status::text), '_', ' ')
      ),
      jsonb_build_object('onboarding_status', v_partner.onboarding_status)
    );
  end if;

  v_code := coalesce(v_partner.partner_code, app.next_partner_code(v_partner.branch_id));

  update public.delivery_partners
  set onboarding_status = 'ACTIVE',
      partner_code = v_code,
      approved_by = auth.uid(),
      approved_at = now(),
      rejection_reason = null,
      suspended_reason = null,
      suspended_until = null,
      -- A newly activated rider starts off duty and chooses when to begin.
      duty_state = 'OFFLINE',
      notes = coalesce(p_note, notes),
      updated_at = now()
  where id = p_delivery_partner_id;

  perform app.audit(
    'UPDATE',
    'delivery_partner',
    p_delivery_partner_id::text,
    jsonb_build_object('onboarding_status', v_partner.onboarding_status),
    jsonb_build_object('onboarding_status', 'ACTIVE', 'partner_code', v_code, 'forced', p_force),
    p_note,
    v_partner.full_name,
    v_partner.branch_id
  );

  perform app.enqueue_notification(
    v_partner.user_id,
    'RIDER_APPROVED',
    jsonb_build_object('partner_code', v_code),
    array['PUSH', 'IN_APP', 'SMS']::public.notification_channel[],
    null,
    format('rider_approved:%s', p_delivery_partner_id)
  );

  return jsonb_build_object(
    'delivery_partner_id', p_delivery_partner_id,
    'onboarding_status', 'ACTIVE',
    'partner_code', v_code,
    'changed', true
  );
end;
$$;

comment on function public.approve_rider is
  'Activates a delivery partner, issues their partner code and audits who approved them.';

create or replace function public.suspend_rider(
  p_delivery_partner_id uuid,
  p_reason text,
  p_until timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_partner public.delivery_partners;
  v_load int;
begin
  select * into v_partner
  from public.delivery_partners
  where id = p_delivery_partner_id and deleted_at is null
  for update;

  if not found then
    perform app.fail('RIDER_NOT_FOUND', 'Delivery partner not found.');
  end if;

  perform app.require_permission('rider.suspend', v_partner.branch_id);

  if btrim(coalesce(p_reason, '')) = '' then
    perform app.fail('CHECKOUT_INVALID', 'Record why this partner is being suspended.');
  end if;

  -- Suspending someone mid-delivery would strand a customer with food in transit
  -- and no one accountable for it. Reassign first.
  v_load := app.rider_active_load(p_delivery_partner_id);
  if v_load > 0 then
    perform app.fail(
      'ACTIVE_DELIVERIES_PENDING',
      format('%s still has %s active delivery(ies). Reassign them first.', v_partner.full_name, v_load),
      jsonb_build_object('active_deliveries', v_load)
    );
  end if;

  update public.delivery_partners
  set onboarding_status = 'SUSPENDED',
      duty_state = 'OFFLINE',
      suspended_reason = p_reason,
      suspended_until = p_until,
      updated_at = now()
  where id = p_delivery_partner_id;

  perform app.audit(
    'RIDER_SUSPEND',
    'delivery_partner',
    p_delivery_partner_id::text,
    jsonb_build_object('onboarding_status', v_partner.onboarding_status),
    jsonb_build_object('onboarding_status', 'SUSPENDED', 'until', p_until),
    p_reason,
    v_partner.full_name,
    v_partner.branch_id
  );

  perform app.enqueue_notification(
    v_partner.user_id,
    'RIDER_SUSPENDED',
    jsonb_build_object('reason', p_reason),
    array['IN_APP']::public.notification_channel[],
    null,
    format('rider_suspended:%s:%s', p_delivery_partner_id, to_char(now(), 'YYYYMMDDHH24MI'))
  );

  return jsonb_build_object(
    'delivery_partner_id', p_delivery_partner_id,
    'onboarding_status', 'SUSPENDED',
    'suspended_until', p_until,
    'cash_in_hand', v_partner.cash_in_hand,
    'changed', true
  );
end;
$$;

comment on function public.suspend_rider is
  'Takes a partner off dispatch. Refuses while they are carrying an order.';

-- ═══════════════════════════════════════════════════════════════════════════
-- EARNINGS ADJUSTMENTS
--
-- `delivery_earnings` allows eight entry types but only two were ever written,
-- and the table is append-only with no client INSERT grant — so an incentive or a
-- cash shortfall could not be recorded at all. This is the only writer for the
-- other six, and it always leaves an audit trail because it moves money.
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function public.post_delivery_earning(
  p_delivery_partner_id uuid,
  p_entry_type text,
  p_amount numeric,
  p_description text default null,
  p_earned_on date default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_partner public.delivery_partners;
  v_amount numeric;
  v_id uuid;
begin
  select * into v_partner
  from public.delivery_partners
  where id = p_delivery_partner_id and deleted_at is null;

  if not found then
    perform app.fail('RIDER_NOT_FOUND', 'Delivery partner not found.');
  end if;

  perform app.require_permission('rider.update', v_partner.branch_id);

  -- DELIVERY_PAYOUT and TIP are derived from a completed delivery; allowing them
  -- here would let an operator inflate a payout that no order justifies.
  if p_entry_type not in (
    'DISTANCE_BONUS', 'SURGE_BONUS', 'INCENTIVE', 'PENALTY', 'ADJUSTMENT', 'CASH_SHORTFALL'
  ) then
    perform app.fail(
      'CHECKOUT_INVALID',
      'That entry type is generated automatically and cannot be posted by hand.',
      jsonb_build_object('entry_type', p_entry_type)
    );
  end if;

  if coalesce(p_amount, 0) = 0 then
    perform app.fail('CHECKOUT_INVALID', 'Enter an amount.');
  end if;

  -- The sign follows the entry type, so a mistyped minus cannot turn a penalty
  -- into a bonus.
  v_amount := case
    when p_entry_type in ('PENALTY', 'CASH_SHORTFALL') then -abs(p_amount)
    when p_entry_type = 'ADJUSTMENT' then p_amount
    else abs(p_amount)
  end;

  insert into public.delivery_earnings (
    delivery_partner_id, entry_type, amount, description, earned_on, created_by
  )
  values (
    p_delivery_partner_id,
    p_entry_type,
    app.money_round(v_amount),
    coalesce(nullif(btrim(p_description), ''), replace(initcap(replace(p_entry_type, '_', ' ')), ' ', ' ')),
    coalesce(p_earned_on, current_date),
    auth.uid()
  )
  returning id into v_id;

  perform app.audit(
    'WALLET_ADJUSTMENT',
    'delivery_earning',
    v_id::text,
    null,
    jsonb_build_object(
      'delivery_partner_id', p_delivery_partner_id,
      'entry_type', p_entry_type,
      'amount', app.money_round(v_amount)
    ),
    p_description,
    v_partner.full_name,
    v_partner.branch_id
  );

  return jsonb_build_object(
    'earning_id', v_id,
    'delivery_partner_id', p_delivery_partner_id,
    'entry_type', p_entry_type,
    'amount', app.money_round(v_amount)
  );
end;
$$;

comment on function public.post_delivery_earning is
  'Posts an incentive, penalty or adjustment to a rider''s ledger. Sign is derived from the entry type.';

-- ═══════════════════════════════════════════════════════════════════════════
-- PEAK PAYOUT & ASSIGNMENT DISTANCE
--
-- `delivery_payout_config.peak_bonus`, `peak_starts_at`, `peak_ends_at` and
-- `delivery_assignments.surge_payout` all existed and were never read or written.
-- A trigger rather than a change to `assign_rider`, so every writer — manual
-- dispatch today, automatic dispatch later — gets the same treatment.
-- ═══════════════════════════════════════════════════════════════════════════
create or replace function app.in_peak_window(
  p_starts time,
  p_ends time,
  p_at timestamptz default now()
)
returns boolean
language sql
stable
set search_path = ''
as $$
  select case
    when p_starts is null or p_ends is null then false
    -- A window that ends before it starts crosses midnight (e.g. 21:00 → 01:00).
    when p_ends < p_starts then (p_at::time >= p_starts or p_at::time < p_ends)
    else p_at::time >= p_starts and p_at::time < p_ends
  end;
$$;

create or replace function app.tg_assignment_payout()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_config public.delivery_payout_config;
  v_store_distance numeric;
begin
  select * into v_config
  from public.delivery_payout_config
  where (branch_id = new.branch_id or branch_id is null) and is_active
  order by branch_id nulls last
  limit 1;

  -- How far the rider was from the outlet when dispatched. Reporting uses it to
  -- judge whether dispatch is picking sensible riders.
  if new.distance_to_store_km is null then
    select app.haversine_km(loc.latitude, loc.longitude, b.latitude, b.longitude)
    into v_store_distance
    from public.delivery_partner_locations loc
    join public.branches b on b.id = new.branch_id
    where loc.delivery_partner_id = new.delivery_partner_id;

    new.distance_to_store_km := round(v_store_distance, 2);
  end if;

  if v_config.id is not null
     and v_config.peak_bonus > 0
     and app.in_peak_window(v_config.peak_starts_at, v_config.peak_ends_at, new.offered_at) then
    new.surge_payout := v_config.peak_bonus;
  end if;

  new.total_payout := app.money_round(
    coalesce(new.base_payout, 0)
    + coalesce(new.distance_payout, 0)
    + coalesce(new.surge_payout, 0)
  );

  return new;
end;
$$;

comment on function app.tg_assignment_payout is
  'Applies the configured peak bonus and records dispatch distance, so every assignment writer agrees on the payout.';

drop trigger if exists assignment_payout on public.delivery_assignments;
create trigger assignment_payout
  before insert on public.delivery_assignments
  for each row execute function app.tg_assignment_payout();

-- ─── Grants ─────────────────────────────────────────────────────────────────
grant execute on function public.my_rider_onboarding() to authenticated;
grant execute on function public.submit_rider_document(
  public.rider_document_type, text, text, date, date
) to authenticated;
grant execute on function public.review_rider_document(uuid, boolean, text) to authenticated;
grant execute on function public.approve_rider(uuid, text, boolean) to authenticated;
grant execute on function public.suspend_rider(uuid, text, timestamptz) to authenticated;
grant execute on function public.post_delivery_earning(uuid, text, numeric, text, date) to authenticated;

-- Documents now travel through `submit_rider_document`, which validates the
-- storage path and drives the onboarding state machine.
revoke insert, update on public.delivery_partner_documents from authenticated;

grant execute on function app.required_rider_documents() to service_role;
grant execute on function app.next_partner_code(uuid) to service_role;
grant execute on function app.in_peak_window(time, time, timestamptz) to service_role;
